require 'fastlane/action'
require_relative '../helper/browserstack_helper'

module Fastlane
  module Actions
    module SharedValues
      BROWSERSTACK_LIVE_APP_ID ||= :BROWSERSTACK_LIVE_APP_ID
    end
    class UploadToBrowserstackAppLiveAction < Action
      SUPPORTED_FILE_EXTENSIONS = ["apk", "ipa", "aab"]
      UPLOAD_API_ENDPOINT = "https://api-cloud.browserstack.com/app-live/upload"

      ARTIFACT_TYPE = "app"
      BS_PRODUCT_TYPE = "AppLive"
      SHARED_VALUE_NAME = "BROWSERSTACK_LIVE_APP_ID"

      def self.run(params)
        args = params.values
        args[:artifact_type] = ARTIFACT_TYPE
        args[:bs_product_type] = BS_PRODUCT_TYPE
        args[:shared_value_name] = SHARED_VALUE_NAME
        args[:supported_file_extensions] = SUPPORTED_FILE_EXTENSIONS
        args[:upload_api_endpoint] = UPLOAD_API_ENDPOINT

        browserstack_app_id = Helper::BrowserstackHelper.upload_file_to_browserstack(args)

        # Setting app id in SharedValues, which can be used by other fastlane actions.
        Actions.lane_context[SharedValues::BROWSERSTACK_LIVE_APP_ID] = browserstack_app_id.to_s
      end

      def self.description
        "Uploads IPA and APK files to BrowserStack AppLive for running manual tests."
      end

      def self.authors
        ["Hitesh Raghuvanshi"]
      end

      def self.details
        "Uploads IPA and APK files to BrowserStack AppLive for running manual tests."
      end

      def self.output
        [
          ['BROWSERSTACK_LIVE_APP_ID', 'App id of uploaded app.']
        ]
      end

      def self.default_file_path
        platform = Actions.lane_context[Actions::SharedValues::PLATFORM_NAME]
        if platform == :ios
          # Shared value for ipa path if it was generated by gym https://docs.fastlane.tools/actions/gym/.
          return Actions.lane_context[Actions::SharedValues::IPA_OUTPUT_PATH]
        else
          # Shared value for apk if it was generated by gradle.
          return Actions.lane_context[Actions::SharedValues::GRADLE_APK_OUTPUT_PATH]
        end
      end

      def self.available_options
        [
          FastlaneCore::ConfigItem.new(key: :browserstack_username,
                                       description: "BrowserStack's username",
                                       optional: false,
                                       is_string: true,
                                       verify_block: proc do |value|
                                         UI.user_error!("No browserstack_username given.") if value.to_s.empty?
                                       end),
          FastlaneCore::ConfigItem.new(key: :browserstack_access_key,
                                       description: "BrowserStack's access key",
                                       optional: false,
                                       is_string: true,
                                       verify_block: proc do |value|
                                         UI.user_error!("No browserstack_access_key given.") if value.to_s.empty?
                                       end),
          FastlaneCore::ConfigItem.new(key: :file_path,
                                       description: "Path to the app file",
                                       optional: true,
                                       is_string: true,
                                       default_value: default_file_path)
        ]
      end

      def self.is_supported?(platform)
        [:ios, :android].include?(platform)
      end

      def self.example_code
        [
          'upload_to_browserstack_app_live',
          'upload_to_browserstack_app_live(
            browserstack_username: ENV["BROWSERSTACK_USERNAME"],
            browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
            file_path: "path_to_apk_or_ipa_file"
           )'
        ]
      end
    end
  end
end
